### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by japhib** [Thundernerd/Unity3D-LayersTagsGenerator#7]
The readme says you can install the package with:

```
openupm add net.tnrd.layerstagsgenerator
```

However, the actual package is under net.tnrd.layertagsgenerator (no S after "layer").

Package looks awesome btw!

**Comment by Thundernerd** [comment]
Oops, that seems to be an issue in the actual package name. Thanks for spotting! I'll update the readme as I don't feel it's smart to change the package name at this stage :).
